# Request
string project_id            # 项目名称
float32[] fl_tcp_position    # 当前法兰的位姿

---
# Response
string message
float32[] pose               # [x, y, z, rx, ry, rz] 机械臂位姿
int32 status_code            # -1 失败, 0 成功