robot_controller:
  ros__parameters:
    # 机器人连接参数
    robot_ip: "192.168.0.122"
    robot_model: "zu12"
    
    # 关节状态发布参数
    joint_states_publish_rate: 125.0  # Hz
    
    # 运动控制参数
    position_tolerance: 0.2  # 度
    servo_step_time: 0.008   # 秒
    
    # 安全参数
    emergency_stop_timeout: 1.0  # 秒
    max_velocity: 100.0  # 度/秒
    
    # 关节名称映射
    joint_names:
      - "joint_1"
      - "joint_2" 
      - "joint_3"
      - "joint_4"
      - "joint_5"
      - "joint_6" 